FROM node:16 as build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN echo "VITE_API_URL=$VITE_API_URL" >> .env.production
RUN echo "VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL" >> .env.production
RUN echo "VITE_VALID_IMAGETYPES_REGEX=$VITE_VALID_IMAGETYPES_REGEX" >> .env.production
RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
