version: "2.2"
services:
    db:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-db-${ENV}
    api:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-api-${ENV}
      build:
        dockerfile: Dockerfile.prod
    client:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-client-${ENV}
      build:
        context: ./Client
        dockerfile: Dockerfile.prod
        args:
          VITE_API_URL: ${VITE_API_URL}
          VITE_SUPPORT_EMAIL: ${VITE_SUPPORT_EMAIL}
          VITE_VALID_IMAGETYPES_REGEX: ${VITE_VALID_IMAGETYPES_REGEX}
