version: "1"
services:
    db:
        image: ticketify-db
        build:
            context: ./Backend
            dockerfile: Dockerfile.db
        restart: always
        ports:
            - 1433:1433
        volumes:
            - ticketify-db-data:/var/opt/mssql/data
        networks:
          - backend
        user:
          root
    api:
      image: ticketify-api
      build:
        context: ./Backend
      ports:
        - 8080:8080
      depends_on:
          db:
            condition: service_healthy
      networks:
        - backend
volumes:
    ticketify-db-data:
        external: true
networks:
  backend:
    driver: bridge
