version: "1"
services:
    db:
        image: ticketify-db
        build:
            context: .\Backend
            dockerfile: Dockerfile.db
        restart: always
        env_file:
            - \Backend\.env
        ports:
            - 1433:1433
        volumes:
            - ticketify-db-data:/var/opt/mssql/data
        networks:
          - backend
        user:
          root
    # todo: make detecting file change working
    api:
      image: ticketify-api
      build:
        context: .\Backend
        dockerfile: Dockerfile.dev
      ports:
        - 8080:8080
      env_file:
        - .\Backend\.env
      volumes:
        - type: bind
          source: .\Backend\src
          target: /app/src
        - /app/node_modules
      depends_on:
          db:
            condition: service_healthy
      networks:
        - backend
    client:
      image: ticketify-client
      build:
        context: .\Client
        dockerfile: Dockerfile.dev
      ports:
        - 3000:3000
      env_file:
        - .\Client\.env
      depends_on:
        - api
      volumes:
        - type: bind
          source: .\Client\src
          target: /app/src
        - /app/node_modules
volumes:
    ticketify-db-data:
        external: true
networks:
  backend:
    driver: bridge
