version: "2.2"
services:
    db:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-db
        restart: always
        ports:
            - 1433:1433
        volumes:
            - ticketify-db-data:/var/opt/mssql/data
        networks:
          - backend
        user:
          root
    api:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-api
      build:
        dockerfile: Dockerfile.prod
      ports:
        - 8080:8080
      depends_on:
          db:
            condition: service_healthy
      networks:
        - backend
    client:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-client
      build:
        context: ./Client
        dockerfile: Dockerfile.prod
        args:
          VITE_API_URL: ${VITE_API_URL}
          VITE_SUPPORT_EMAIL: ${VITE_SUPPORT_EMAIL}
          VITE_VALID_IMAGETYPES_REGEX: ${VITE_VALID_IMAGETYPES_REGEX}
      ports:
        - 3000:80
      depends_on:
        - api
volumes:
    ticketify-db-data:
        external: true
networks:
  backend:
    driver: bridge
