version: "1"
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        env_file:
            - .db.env
        ports:
            - 1433:1433
        volumes:
            - db-data:/var/opt/mssql/data
        networks:
          - backend
        user:
          root
    # todo: make detecting file change working
    api:
      image: ticketify_api
      build:
        context: ./Backend
        dockerfile: Dockerfile.dev
      ports:
        - 8080:8080
      env_file:
        - ./Backend/.env
      volumes:
        - type: bind
          source: .\Backend\src
          target: /app/src
        - /app/node_modules
      environment:
        CHOKIDAR_USEPOLLING: true
      depends_on:
        - db
      networks:
        - backend
    client:
      image: ticketify_client
      build:
        context: ./Client
        dockerfile: Dockerfile.dev
      ports:
        - 3000:3000
      env_file:
        - ./Client/.env
      depends_on:
        - api
      volumes:
        - type: bind
          source: .\Client\src
          target: /app/src
        - /app/node_modules
      environment:
        CHOKIDAR_USEPOLLING: true
volumes:
    db-data:
networks:
  backend:
    driver: bridge
