version: "2.2"
services:
    db:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-db-${ENV}
        restart: always
        ports:
            - 1433:1433
        volumes:
            - ticketify-db-data:/var/opt/mssql/data
        networks:
          - backend
        user:
          root
        environment:
          - ACCEPT_EULA=${ACCEPT_EULA}
          - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    api:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-api-${ENV}
      ports:
        - 8080:8080
      depends_on:
          db:
            condition: service_healthy
      networks:
        - backend
      environment:
        - PORT=${PORT}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        - FILE_IMAGE_MAX_COUNT=${FILE_IMAGE_MAX_COUNT}
        - FILE_IMAGE_MAX_SIZE_KB=${FILE_IMAGE_MAX_SIZE_KB}
        - FILE_MAX_COUNT=${FILE_MAX_COUNT}
        - FILE_MAX_SIZE_KB=${FILE_MAX_SIZE_KB}
        - FILE_SIGNED_URL_EXPIRING_IN_SECONDS=${FILE_SIGNED_URL_EXPIRING_IN_SECONDS}
        - S3_PUBLIC_KEY=${S3_PUBLIC_KEY}
        - S3_PRIVATE_KEY=${S3_PRIVATE_KEY}
        - S3_BUCKET_NAME=${S3_BUCKET_NAME}
        - S3_REGION=${S3_REGION}
        - SMTP_USERNAME=${SMTP_USERNAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - SUPPORT_EMAIL=${SUPPORT_EMAIL}
        - VALID_IMAGETYPES_REGEX=${VALID_IMAGETYPES_REGEX}
        - DATABASE_URL=${DATABASE_URL}
    client:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ticketify-client-${ENV}
      ports:
        - 3000:80
      depends_on:
        - api
volumes:
    ticketify-db-data:
        external: true
networks:
  backend:
    driver: bridge
