BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Test] (
    [id] INT NOT NULL IDENTITY(1,1),
    [isAmazing] BIT NOT NULL,
    [description] NVARCHAR(100) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Test_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Test_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
