###
POST {{host}}/ticketOnTicket
Content-Type: application/json
auth-token: {{auth-token}}

{
    "connectedByTicketId": "29",
    "connectedToTicketId": "30"
}

###
DELETE {{host}}/ticketOnTicket/29/30
auth-token: {{auth-token}}