BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[UserSettings] ADD [createUser] NVARCHAR(100),
[createdAt] DATETIME2 CONSTRAINT [UserSettings_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[updateUser] NVARCHAR(100),
[updatedAt] DATETIME2;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
